-- Run this entire script in Supabase Dashboard > SQL Editor.
-- The final notification refreshes PostgREST's function schema cache.

create table if not exists public.messages (
    id bigint generated by default as identity primary key,
    name text not null check (char_length(trim(name)) between 1 and 100),
    contact text not null default '' check (char_length(contact) <= 200),
    content text not null check (char_length(trim(content)) between 1 and 600),
    image_url text not null default '',
    link_url text not null default '' check (link_url = '' or link_url ~* '^https?://'),
    created_at timestamptz not null default now()
);

alter table public.messages add column if not exists image_url text not null default '';
alter table public.messages add column if not exists link_url text not null default '';

-- Store only bcrypt hashes. Insert the administrator's hash manually below.
create schema if not exists extensions;
create extension if not exists pgcrypto with schema extensions;
create table if not exists public.site_access_codes (
    id bigint generated by default as identity primary key,
    password_hash text not null,
    role text not null default 'normal' check (role in ('normal', 'admin')),
    enabled boolean not null default true,
    created_at timestamptz not null default now()
);

alter table public.site_access_codes add column if not exists role text not null default 'normal';

create table if not exists public.site_access_grants (
    id bigint generated by default as identity primary key,
    token_hash text unique not null,
    role text not null check (role in ('normal', 'admin')),
    expires_at timestamptz not null,
    created_at timestamptz not null default now()
);

create table if not exists public.recommendation_links (
    id bigint generated by default as identity primary key,
    title text not null check (char_length(trim(title)) between 1 and 100),
    url text not null check (url ~* '^https?://'),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.category_links (
    id bigint generated by default as identity primary key,
    category_id text not null check (category_id in ('contact', 'study', 'ai', 'article')),
    title text not null check (char_length(trim(title)) between 1 and 100),
    url text not null default '',
    display_order int not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

alter table public.category_links drop constraint if exists category_links_url_check;

create index if not exists idx_category_links_category on public.category_links(category_id, display_order, created_at);

alter table public.site_access_codes enable row level security;
revoke all on public.site_access_codes from anon, authenticated;
alter table public.site_access_grants enable row level security;
revoke all on public.site_access_grants from anon, authenticated;
alter table public.recommendation_links enable row level security;
revoke all on public.recommendation_links from anon, authenticated;
alter table public.category_links enable row level security;
revoke all on public.category_links from anon, authenticated;

alter table public.messages enable row level security;

drop policy if exists "Anyone can read messages" on public.messages;
create policy "Anyone can read messages"
on public.messages for select
to anon, authenticated
using (true);

revoke insert, update, delete on public.messages from anon, authenticated;

insert into storage.buckets (id, name, public)
values ('message-images', 'message-images', true)
on conflict (id) do update set public = true;

drop policy if exists "Anyone can view message images" on storage.objects;
create policy "Anyone can view message images"
on storage.objects for select
to anon, authenticated
using (bucket_id = 'message-images');

drop policy if exists "Users can upload own message images" on storage.objects;
create policy "Users can upload own message images"
on storage.objects for insert
to anon, authenticated
with check (
    bucket_id = 'message-images'
    and (
        (select auth.uid()::text) = (storage.foldername(name))[1]
        or ((select auth.uid()) is null and (storage.foldername(name))[1] = 'guest')
    )
);

drop function if exists public.submit_message(text, text, text, text, text);
drop function if exists public.submit_message(text, text, text);
create or replace function public.submit_message(
    p_name text,
    p_contact text,
    p_content text,
    p_image_url text default '',
    p_link_url text default ''
)
returns public.messages
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
    new_message public.messages;
    normalized_name text := trim(coalesce(p_name, ''));
    normalized_contact text := trim(coalesce(p_contact, ''));
    normalized_content text := trim(coalesce(p_content, ''));
    normalized_image_url text := trim(coalesce(p_image_url, ''));
    normalized_link_url text := trim(coalesce(p_link_url, ''));
begin
    if char_length(normalized_name) < 1 or char_length(normalized_name) > 100 then
        raise exception '姓名长度必须为 1 到 100 个字符';
    end if;

    if char_length(normalized_contact) > 200 then
        raise exception '联系方式不能超过 200 个字符';
    end if;

    if char_length(normalized_content) < 1 or char_length(normalized_content) > 600 then
        raise exception '留言长度必须为 1 到 600 个字符';
    end if;

    if normalized_link_url <> '' and normalized_link_url !~* '^https?://' then
        raise exception '留言链接必须以 http:// 或 https:// 开头';
    end if;

    if (
        select count(*)
        from public.messages
        where lower(trim(name)) = lower(normalized_name)
          and created_at > now() - interval '30 minutes'
    ) >= 3 then
        raise exception '同一个名字半小时内最多留言 3 条';
    end if;

    insert into public.messages (name, contact, content, image_url, link_url)
    values (normalized_name, normalized_contact, normalized_content, normalized_image_url, normalized_link_url)
    returning * into new_message;

    return new_message;
end;
$$;

grant execute on function public.submit_message(text, text, text, text, text) to anon, authenticated;

drop function if exists public.access_role(text);
create or replace function public.access_role(p_access_token text)
returns text
language sql
security definer
set search_path = public, extensions
as $$
    select role
    from public.site_access_grants
    where token_hash = encode(digest(coalesce(p_access_token, ''), 'sha256'), 'hex')
      and expires_at > now()
    limit 1;
$$;

drop function if exists public.verify_site_password(text);
create or replace function public.verify_site_password(p_password text)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
    matched_role text;
    raw_token text := encode(gen_random_bytes(32), 'hex');
begin
    select role into matched_role
    from public.site_access_codes
    where enabled = true
      and password_hash = crypt(coalesce(p_password, ''), password_hash)
    limit 1;

    if matched_role is null then
        return jsonb_build_object('granted', false);
    end if;

    insert into public.site_access_grants (token_hash, role, expires_at)
    values (
        encode(digest(raw_token, 'sha256'), 'hex'),
        matched_role,
        now() + interval '30 days'
    );

    return jsonb_build_object('granted', true, 'role', matched_role, 'token', raw_token);
end;
$$;

drop function if exists public.get_recommendations(text);
create or replace function public.get_recommendations(p_access_token text)
returns setof public.recommendation_links
language plpgsql
security definer
set search_path = public, extensions
as $$
begin
    if public.access_role(p_access_token) is null then
        raise exception '访问暗号已失效，请重新验证';
    end if;
    return query select * from public.recommendation_links order by created_at asc;
end;
$$;

drop function if exists public.get_recommendation(text, bigint);
create or replace function public.get_recommendation(p_access_token text, p_id bigint)
returns public.recommendation_links
language plpgsql
security definer
set search_path = public, extensions
as $$
declare result public.recommendation_links;
begin
    if public.access_role(p_access_token) <> 'admin' then
        raise exception '需要管理员暗号';
    end if;
    select * into result from public.recommendation_links where id = p_id;
    return result;
end;
$$;

drop function if exists public.admin_upsert_recommendation(text, bigint, text, text);
create or replace function public.admin_upsert_recommendation(
    p_access_token text,
    p_id bigint,
    p_title text,
    p_url text
)
returns public.recommendation_links
language plpgsql
security definer
set search_path = public, extensions
as $$
declare result public.recommendation_links;
begin
    if public.access_role(p_access_token) <> 'admin' then
        raise exception '需要管理员暗号';
    end if;
    if p_url !~* '^https?://' then
        raise exception '链接必须以 http:// 或 https:// 开头';
    end if;
    if p_id is null then
        insert into public.recommendation_links (title, url)
        values (trim(p_title), trim(p_url)) returning * into result;
    else
        update public.recommendation_links
        set title = trim(p_title), url = trim(p_url), updated_at = now()
        where id = p_id returning * into result;
    end if;
    return result;
end;
$$;

drop function if exists public.admin_delete_recommendation(text, bigint);
create or replace function public.admin_delete_recommendation(p_access_token text, p_id bigint)
returns boolean
language plpgsql
security definer
set search_path = public, extensions
as $$
begin
    if public.access_role(p_access_token) <> 'admin' then
        raise exception '需要管理员暗号';
    end if;
    delete from public.recommendation_links where id = p_id;
    return found;
end;
$$;

drop function if exists public.admin_delete_message(text, bigint);
create or replace function public.admin_delete_message(p_access_token text, p_id bigint)
returns boolean
language plpgsql
security definer
set search_path = public, extensions
as $$
begin
    if public.access_role(p_access_token) <> 'admin' then
        raise exception '需要管理员暗号';
    end if;
    delete from public.messages where id = p_id;
    return found;
end;
$$;

drop function if exists public.admin_update_normal_password(text, text);
create or replace function public.admin_update_normal_password(
    p_access_token text,
    p_new_password text
)
returns boolean
language plpgsql
security definer
set search_path = public, extensions
as $$
begin
    if public.access_role(p_access_token) <> 'admin' then
        raise exception '需要管理员暗号';
    end if;
    if char_length(coalesce(p_new_password, '')) < 6 then
        raise exception '普通暗号至少需要 6 个字符';
    end if;

    delete from public.site_access_codes where role = 'normal';
    insert into public.site_access_codes (password_hash, role)
    values (crypt(p_new_password, gen_salt('bf')), 'normal');
    return true;
end;
$$;

drop function if exists public.get_category_links(text, text);
drop function if exists public.get_category_links(text);
create or replace function public.get_category_links(p_category_id text)
returns setof public.category_links
language sql
security definer
set search_path = public, extensions
as $$
    select * from public.category_links
    where category_id = p_category_id
    order by display_order asc, created_at asc;
$$;

drop function if exists public.admin_upsert_category_link(text, bigint, text, text, text, int);
create or replace function public.admin_upsert_category_link(
    p_access_token text,
    p_id bigint,
    p_category_id text,
    p_title text,
    p_url text,
    p_display_order int default 0
)
returns public.category_links
language plpgsql
security definer
set search_path = public, extensions
as $$
declare result public.category_links;
begin
    if public.access_role(p_access_token) <> 'admin' then
        raise exception '需要管理员暗号';
    end if;
    if p_category_id <> 'contact' and p_url <> '' and p_url !~* '^https?://' then
        raise exception '链接必须以 http:// 或 https:// 开头';
    end if;
    if p_id is null then
        insert into public.category_links (category_id, title, url, display_order)
        values (p_category_id, trim(p_title), trim(p_url), p_display_order) returning * into result;
    else
        update public.category_links
        set title = trim(p_title), url = trim(p_url), display_order = p_display_order, updated_at = now()
        where id = p_id returning * into result;
    end if;
    return result;
end;
$$;

drop function if exists public.admin_delete_category_link(text, bigint);
create or replace function public.admin_delete_category_link(p_access_token text, p_id bigint)
returns boolean
language plpgsql
security definer
set search_path = public, extensions
as $$
begin
    if public.access_role(p_access_token) <> 'admin' then
        raise exception '需要管理员暗号';
    end if;
    delete from public.category_links where id = p_id;
    return found;
end;
$$;

/*
    The public table is intentionally not readable directly. All protected reads
    and admin mutations go through the RPC functions above.
*/

/* Keep the old verification query shape out of the schema cache. */
/*
    select exists (
        select 1
        from public.site_access_codes
        where enabled = true
          and password_hash = crypt(coalesce(p_password, ''), password_hash)
    );
*/

revoke all on function public.access_role(text) from public;
revoke all on function public.verify_site_password(text) from public;
revoke all on function public.get_recommendations(text) from public;
revoke all on function public.get_recommendation(text, bigint) from public;
revoke all on function public.admin_upsert_recommendation(text, bigint, text, text) from public;
revoke all on function public.admin_delete_recommendation(text, bigint) from public;
revoke all on function public.admin_delete_message(text, bigint) from public;
revoke all on function public.admin_update_normal_password(text, text) from public;
revoke all on function public.get_category_links(text) from public;
revoke all on function public.admin_upsert_category_link(text, bigint, text, text, text, int) from public;
revoke all on function public.admin_delete_category_link(text, bigint) from public;
grant execute on function public.access_role(text) to anon, authenticated;
grant execute on function public.verify_site_password(text) to anon, authenticated;
grant execute on function public.get_recommendations(text) to anon, authenticated;
grant execute on function public.get_recommendation(text, bigint) to anon, authenticated;
grant execute on function public.admin_upsert_recommendation(text, bigint, text, text) to anon, authenticated;
grant execute on function public.admin_delete_recommendation(text, bigint) to anon, authenticated;
grant execute on function public.admin_delete_message(text, bigint) to anon, authenticated;
grant execute on function public.admin_update_normal_password(text, text) to anon, authenticated;
grant execute on function public.get_category_links(text) to anon, authenticated;
grant execute on function public.admin_upsert_category_link(text, bigint, text, text, text, int) to anon, authenticated;
grant execute on function public.admin_delete_category_link(text, bigint) to anon, authenticated;

select pg_notify('pgrst', 'reload schema');

-- After choosing a password, run this separately (replace the example text):
-- insert into public.site_access_codes (password_hash)
-- values (crypt('replace-with-your-secret', gen_salt('bf')));

-- Create the two access codes with their roles:
-- insert into public.site_access_codes (password_hash, role) values
--     (crypt('replace-with-normal-code', gen_salt('bf')), 'normal'),
--     (crypt('replace-with-admin-code', gen_salt('bf')), 'admin');
